name: user-management
app: python@3.9
options:
  env:
    - name: FLASK_ENV
      value: production
  install: pip install -r requirements.txt
  start: gunicorn --bind 0.0.0.0:$PORT --workers 2 app:app
ports: 5000/http
context:
  git:
    url: https://github.com/Aimyonnnnn/users.git
    branch: main
